### ISSUE TITLE
Unclear how to enable profiling

### ISSUE THREAD

**Issue by thijsc** [gnzlbg/jemallocator#115]
I'm trying to get jemalloc to do heap profiling by configuring it in the environment:

```bash
export MALLOC_CONF=prof:true,lg_prof_interval:30,lg_prof_sample:17
```

Profiling is enabled:

```toml
[dependencies.jemallocator]
version = "*"
features = ["profiling"]
```

I do not see the expected output as described [here](https://github.com/jemalloc/jemalloc/wiki/Use-Case:-Leak-Checking). Is this expected to work when using this crate?
