### ISSUE TITLE
Update version number in readme

### ISSUE THREAD

**Issue by dtolnay** [gnzlbg/jemallocator#116]
The most recent release is 0.3.0 but the readme still shows:

```toml
[dependencies]
jemallocator = "0.1.8"
```

Maybe add a comment next to the version number in Cargo.toml as a reminder to bump the version number in the readme when releasing breaking changes.
